const COBRANZA_FILE = 'data/Para_Tablero_EPAS.xlsx';
const WORKS_FILE = 'data/Control_GDE_obras_a_licitar.xlsx';
const CONTRACTS_FILE = 'data/Contratos_vigentes_cuadrillas_servicios.xlsx';

const ARS = new Intl.NumberFormat('es-AR', { style:'currency', currency:'ARS', maximumFractionDigits:0 });
const NUM = new Intl.NumberFormat('es-AR', { maximumFractionDigits:0 });
const PCT = new Intl.NumberFormat('es-AR', { minimumFractionDigits:1, maximumFractionDigits:1 });
const DATE_FMT = new Intl.DateTimeFormat('es-AR', { day:'2-digit', month:'2-digit', year:'numeric' });

const state = { collection:{period:'—',rows:[],cities:[]}, works:[], contracts:[], processContracts:[], charts:{} };

function cleanText(v){ return String(v ?? '').replace(/\s+/g,' ').trim(); }
function numeric(v){ if(typeof v==='string'){ const n=Number(v.replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,'')); return Number.isFinite(n)?n:0; } const n=Number(v); return Number.isFinite(n)?n:0; }
function escapeHtml(s){ return String(s ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
function fmtMoney(v){ return ARS.format(numeric(v)); }
function fmtCompactMoney(v){ const n=numeric(v),a=Math.abs(n); if(a>=1e9)return `$ ${PCT.format(n/1e9)} mil M`; if(a>=1e6)return `$ ${PCT.format(n/1e6)} M`; return fmtMoney(n); }
function fmtDate(d){ return d instanceof Date&&!isNaN(d)?DATE_FMT.format(d):'—'; }
function updateTimestamp(el){ el.textContent=`Actualizado ${new Date().toLocaleString('es-AR',{dateStyle:'short',timeStyle:'short'})}`; }
function startOfToday(){ const d=new Date(); return new Date(d.getFullYear(),d.getMonth(),d.getDate()); }
function daysBetween(a,b){ return Math.ceil((b-a)/86400000); }
function staffNumber(v){ const s=cleanText(v); if(!s)return 0; const nums=[...s.matchAll(/\d+/g)].map(m=>Number(m[0])); return nums.reduce((a,b)=>a+b,0); }

for(const btn of document.querySelectorAll('.tab-button')) btn.addEventListener('click',()=>{document.querySelectorAll('.tab-button').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.tab-content').forEach(s=>s.classList.remove('active'));btn.classList.add('active');document.getElementById(`tab-${btn.dataset.tab}`).classList.add('active');setTimeout(()=>Object.values(state.charts).forEach(c=>c?.resize()),50);});
for(const btn of document.querySelectorAll('.subtab-button')) btn.addEventListener('click',()=>{document.querySelectorAll('.subtab-button').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.contract-view').forEach(s=>s.classList.remove('active'));btn.classList.add('active');document.getElementById(`contract-view-${btn.dataset.contractView}`).classList.add('active');setTimeout(()=>Object.values(state.charts).forEach(c=>c?.resize()),50);});

async function loadArrayBuffer(url){ const response=await fetch(url,{cache:'no-store'}); if(!response.ok)throw new Error(`No se pudo cargar ${url}`); return response.arrayBuffer(); }
function excelDateToJS(v){ if(v instanceof Date)return new Date(v.getFullYear(),v.getMonth(),v.getDate()); if(typeof v==='number'){const p=XLSX.SSF.parse_date_code(v);if(p)return new Date(p.y,p.m-1,p.d);} if(typeof v==='string'&&v.trim()){const s=v.trim();const m=s.match(/^(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{2,4})$/);if(m){const y=+m[3]<100?2000+(+m[3]):+m[3];return new Date(y,+m[2]-1,+m[1]);}const d=new Date(s);if(!isNaN(d))return d;} return null; }
function parseDateFromText(v){ const s=cleanText(v); const m=s.match(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})/); return m?new Date(+m[3],+m[2]-1,+m[1]):null; }
function destroyChart(name){if(state.charts[name]){state.charts[name].destroy();state.charts[name]=null;}}
function createBar(name,canvasId,labels,data,horizontal=false){destroyChart(name);state.charts[name]=new Chart(document.getElementById(canvasId),{type:'bar',data:{labels,datasets:[{data,borderRadius:7,maxBarThickness:52}]},options:{responsive:true,maintainAspectRatio:false,indexAxis:horizontal?'y':'x',plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>fmtMoney(c.raw)}}},scales:{x:{grid:{display:!horizontal},ticks:{callback:horizontal?v=>fmtCompactMoney(v):undefined}},y:{grid:{display:horizontal?false:true},ticks:{callback:horizontal?undefined:v=>fmtCompactMoney(v)}}}}});}
function createDoughnut(name,canvasId,labels,data){destroyChart(name);state.charts[name]=new Chart(document.getElementById(canvasId),{type:'doughnut',data:{labels,datasets:[{data,borderWidth:2,borderColor:'#fff'}]},options:{responsive:true,maintainAspectRatio:false,cutout:'62%',plugins:{legend:{position:'bottom',labels:{boxWidth:10,usePointStyle:true}},tooltip:{callbacks:{label:c=>`${c.label}: ${fmtMoney(c.raw)}`}}}}});}

// Cobranza
function parseCollection(buffer){const wb=XLSX.read(buffer,{type:'array',cellDates:true}),ws=wb.Sheets[wb.SheetNames[0]],matrix=XLSX.utils.sheet_to_json(ws,{header:1,defval:null,raw:true});if(!matrix.length)throw new Error('El Excel de cobranza está vacío.');const header=matrix[0].map(cleanText),agentIdx=header.findIndex(h=>h.toLowerCase()==='agente de cobro'),totalIdx=header.findIndex(h=>h.toLowerCase()==='total general');if(agentIdx<0||totalIdx<0||totalIdx<=agentIdx)throw new Error('No encuentro las columnas “Agente de cobro” y “Total General”.');const period=cleanText(matrix[0][0])||'—',cities=header.slice(agentIdx+1,totalIdx).filter(Boolean),rows=[];for(let r=1;r<matrix.length;r++){const agent=cleanText(matrix[r][agentIdx]);if(!agent||/^total/i.test(agent))continue;cities.forEach((city,i)=>{const amount=numeric(matrix[r][agentIdx+1+i]);if(amount!==0)rows.push({agent,city,amount});});}return{period,cities,rows};}
function populateCollectionFilters(){const citySel=document.getElementById('cityFilter'),channelSel=document.getElementById('channelFilter'),currentCity=citySel.value,currentChannel=channelSel.value;citySel.innerHTML='<option value="ALL">Todas</option>'+state.collection.cities.map(c=>`<option>${escapeHtml(c)}</option>`).join('');const agents=[...new Set(state.collection.rows.map(r=>r.agent))].sort((a,b)=>a.localeCompare(b,'es'));channelSel.innerHTML='<option value="ALL">Todos</option>'+agents.map(a=>`<option>${escapeHtml(a)}</option>`).join('');if([...citySel.options].some(o=>o.value===currentCity))citySel.value=currentCity;if([...channelSel.options].some(o=>o.value===currentChannel))channelSel.value=currentChannel;}
function aggregate(rows,key){const m=new Map();rows.forEach(r=>m.set(r[key],(m.get(r[key])||0)+r.amount));return[...m.entries()].map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value);}
function renderCollection(){const city=document.getElementById('cityFilter').value,agent=document.getElementById('channelFilter').value,rows=state.collection.rows.filter(r=>(city==='ALL'||r.city===city)&&(agent==='ALL'||r.agent===agent)),total=rows.reduce((s,r)=>s+r.amount,0),byCity=aggregate(rows,'city'),byAgent=aggregate(rows,'agent');document.getElementById('periodTitle').textContent=`Período ${state.collection.period}`;document.getElementById('periodFilter').textContent=state.collection.period;document.getElementById('kpiCollected').textContent=fmtCompactMoney(total);document.getElementById('kpiTopChannel').textContent=byAgent[0]?.name||'—';document.getElementById('kpiTopChannelShare').textContent=byAgent[0]&&total?`${PCT.format(byAgent[0].value/total*100)} % del total`:'—';document.getElementById('kpiTopCity').textContent=byCity[0]?.name||'—';document.getElementById('kpiTopCityAmount').textContent=byCity[0]?fmtCompactMoney(byCity[0].value):'—';document.getElementById('kpiCities').textContent=NUM.format(byCity.filter(x=>x.value>0).length);document.getElementById('tableTotal').textContent=`Total: ${fmtMoney(total)}`;createBar('cityChart','cityChart',byCity.map(x=>x.name),byCity.map(x=>x.value),byCity.length>=6);createBar('channelChart','channelChart',byAgent.slice(0,10).map(x=>x.name),byAgent.slice(0,10).map(x=>x.value),true);createDoughnut('cityShareChart','cityShareChart',byCity.map(x=>x.name),byCity.map(x=>x.value));const body=document.getElementById('detailBody'),sorted=[...rows].sort((a,b)=>b.amount-a.amount);body.innerHTML=sorted.length?sorted.map(r=>`<tr><td>${escapeHtml(r.agent)}</td><td>${escapeHtml(r.city)}</td><td class="numeric">${fmtMoney(r.amount)}</td><td class="numeric">${total?PCT.format(r.amount/total*100):'0,0'} %</td></tr>`).join(''):'<tr><td class="empty-row" colspan="4">Sin datos para los filtros seleccionados.</td></tr>';}
async function loadDefaultCollection(){const status=document.getElementById('fileStatus');status.textContent='Cargando archivo base…';try{const b=await loadArrayBuffer(COBRANZA_FILE);state.collection=parseCollection(b);populateCollectionFilters();renderCollection();status.textContent='Archivo base de cobranza cargado';updateTimestamp(document.getElementById('lastUpdate'));}catch(e){status.textContent=`Error: ${e.message}`;console.error(e);}}

// Obras
function parseWorks(buffer){const wb=XLSX.read(buffer,{type:'array',cellDates:true}),ws=wb.Sheets['Exptes']||wb.Sheets[wb.SheetNames[0]],matrix=XLSX.utils.sheet_to_json(ws,{header:1,defval:null,raw:true});let hi=matrix.findIndex(row=>row.some(v=>cleanText(v).toLowerCase().includes('expediente'))&&row.some(v=>cleanText(v).toLowerCase().includes('nombre de la obra')));if(hi<0)throw new Error('No encuentro los encabezados de la hoja de obras.');const h=matrix[hi].map(v=>cleanText(v).toLowerCase()),idx=needle=>h.findIndex(x=>x.includes(needle)),e=idx('expediente'),n=idx('nombre de la obra'),l=idx('localidad'),f=idx('fecha apertura'),p=idx('presupuesto oficial'),a=idx('adjudicado');if([e,n,l,p].some(i=>i<0))throw new Error('Faltan columnas obligatorias en el Excel de obras.');const out=[];for(let r=hi+1;r<matrix.length;r++){const exp=cleanText(matrix[r][e]),name=cleanText(matrix[r][n]);if(!exp&&!name)continue;out.push({expediente:exp,obra:name,localidad:cleanText(matrix[r][l])||'Sin localidad',apertura:f>=0?excelDateToJS(matrix[r][f]):null,presupuesto:numeric(matrix[r][p]),adjudicado:a>=0?numeric(matrix[r][a]):0});}return out;}
function workStatus(w){if(w.adjudicado)return{code:'ADJUDICADA',label:'Adjudicada',cls:'adjudicada'};if(!w.apertura)return{code:'SIN_FECHA',label:'Sin fecha definida',cls:'sin-fecha'};const days=Math.ceil((w.apertura-startOfToday())/86400000);if(days<0)return{code:'VENCIDA',label:'Apertura vencida',cls:'vencida'};if(days<=7)return{code:'PROXIMA',label:days===0?'Apertura hoy':`Apertura en ${days} día${days===1?'':'s'}`,cls:'proxima'};return{code:'PROGRAMADA',label:'Apertura programada',cls:'programada'};}
function populateWorksFilters(){const sel=document.getElementById('worksCityFilter'),cur=sel.value,cities=[...new Set(state.works.map(w=>w.localidad))].sort((a,b)=>a.localeCompare(b,'es'));sel.innerHTML='<option value="ALL">Todas</option>'+cities.map(c=>`<option>${escapeHtml(c)}</option>`).join('');if([...sel.options].some(o=>o.value===cur))sel.value=cur;}
function filteredWorks(){const city=document.getElementById('worksCityFilter').value,status=document.getElementById('worksStatusFilter').value,q=cleanText(document.getElementById('worksSearch').value).toLowerCase();return state.works.filter(w=>{const st=workStatus(w);return(city==='ALL'||w.localidad===city)&&(status==='ALL'||st.code===status)&&(!q||`${w.expediente} ${w.obra}`.toLowerCase().includes(q));});}
function renderWorksStatusSummary(rows){const defs=[['ADJUDICADA','Adjudicadas','adjudicada'],['VENCIDA','Aperturas vencidas','vencida'],['PROXIMA','Aperturas próximas (≤ 7 días)','proxima'],['PROGRAMADA','Aperturas programadas','programada'],['SIN_FECHA','Sin fecha definida','sin-fecha']],counts=Object.fromEntries(defs.map(([c])=>[c,0]));rows.forEach(w=>counts[workStatus(w).code]++);document.getElementById('worksStatusCards').innerHTML=defs.map(([c,label,cls])=>`<div class="status-row"><div class="left"><span class="dot ${cls}"></span><strong>${label}</strong></div><span class="count">${counts[c]}</span></div>`).join('');}
function renderWorks(){const rows=filteredWorks(),budget=rows.reduce((s,w)=>s+w.presupuesto,0),withOpen=rows.filter(w=>w.apertura),awarded=rows.filter(w=>workStatus(w).code==='ADJUDICADA');document.getElementById('kpiWorks').textContent=NUM.format(rows.length);document.getElementById('kpiBudget').textContent=fmtCompactMoney(budget);document.getElementById('kpiOpenings').textContent=NUM.format(withOpen.length);const future=withOpen.filter(w=>w.apertura>=startOfToday()).sort((a,b)=>a.apertura-b.apertura);document.getElementById('kpiNextOpening').textContent=future[0]?`Próxima: ${fmtDate(future[0].apertura)}`:'Próxima: —';document.getElementById('kpiAwarded').textContent=NUM.format(awarded.length);document.getElementById('kpiAwardedShare').textContent=`${rows.length?PCT.format(awarded.length/rows.length*100):'0,0'} % del total`;document.getElementById('worksTableTotal').textContent=`${rows.length} obra${rows.length===1?'':'s'} · ${fmtCompactMoney(budget)}`;renderWorksStatusSummary(rows);const byCity=new Map();rows.forEach(w=>byCity.set(w.localidad,(byCity.get(w.localidad)||0)+w.presupuesto));const cityData=[...byCity.entries()].map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value);createBar('worksCityChart','worksCityChart',cityData.map(x=>x.name),cityData.map(x=>x.value),cityData.length>=6);const body=document.getElementById('worksBody'),sorted=[...rows].sort((a,b)=>{if(a.apertura&&b.apertura)return a.apertura-b.apertura;if(a.apertura)return-1;if(b.apertura)return 1;return b.presupuesto-a.presupuesto;});body.innerHTML=sorted.length?sorted.map(w=>{const st=workStatus(w);return`<tr><td class="exp-cell">${escapeHtml(w.expediente)}</td><td class="work-name">${escapeHtml(w.obra)}</td><td>${escapeHtml(w.localidad)}</td><td>${fmtDate(w.apertura)}</td><td class="numeric">${fmtMoney(w.presupuesto)}</td><td><span class="status-pill ${st.cls}">${escapeHtml(st.label)}</span></td><td class="numeric">${w.adjudicado>0?fmtMoney(w.adjudicado):'—'}</td></tr>`;}).join(''):'<tr><td class="empty-row" colspan="7">Sin obras para los filtros seleccionados.</td></tr>';}
async function loadDefaultWorks(){const status=document.getElementById('worksFileStatus');status.textContent='Cargando archivo de obras…';try{const b=await loadArrayBuffer(WORKS_FILE);state.works=parseWorks(b);populateWorksFilters();renderWorks();status.textContent='Archivo base de obras cargado';document.getElementById('worksBadge').textContent=state.works.length;updateTimestamp(document.getElementById('worksLastUpdate'));}catch(e){status.textContent=`Error: ${e.message}`;console.error(e);}}

// Contratos y servicios
function parseContracts(buffer){
  const wb=XLSX.read(buffer,{type:'array',cellDates:true});
  const ws=wb.Sheets['Contratos']||wb.Sheets[wb.SheetNames[0]];
  const matrix=XLSX.utils.sheet_to_json(ws,{header:1,defval:null,raw:true});
  const out=[]; let last=null;
  for(let r=2;r<matrix.length;r++){
    const row=matrix[r],localidad=cleanText(row[0]),contrato=cleanText(row[1]),expediente=cleanText(row[2]);
    const inicio=excelDateToJS(row[6]),fin=excelDateToJS(row[7]);
    if(!localidad&&!contrato&&!expediente){
      if(last&&(inicio||fin)){ if(inicio)last.extensionStart=inicio; if(fin){last.extensionEnd=fin;last.finalEfectiva=fin;} }
      continue;
    }
    if(!contrato&&!expediente)continue;
    const note=cleanText(row[8]),textEnd=parseDateFromText(note);
    const item={localidad:localidad||'Sin localidad',contrato,expediente,adjudicado:numeric(row[3]),empresa:cleanText(row[4])||'—',plazo:numeric(row[5]),inicio,final:fin,finalEfectiva:textEnd||fin,nuevaTramitacion:note,extensionStart:null,extensionEnd:null};
    out.push(item);last=item;
  }
  return out;
}
function parseProcessContracts(buffer){
  const wb=XLSX.read(buffer,{type:'array',cellDates:true}),ws=wb.Sheets['En proceso'];if(!ws)return[];
  const matrix=XLSX.utils.sheet_to_json(ws,{header:1,defval:null,raw:true}),out=[];
  for(let r=2;r<matrix.length;r++){
    const row=matrix[r],contrato=cleanText(row[1]),expediente=cleanText(row[2]);if(!contrato&&!expediente)continue;
    out.push({localidad:cleanText(row[0])||'Sin localidad',contrato,expediente,presupuesto:numeric(row[3]),adjudicado:numeric(row[4]),empresa:cleanText(row[6]),plazo:numeric(row[7]),inicio:excelDateToJS(row[11]),final:excelDateToJS(row[12])});
  }
  return out;
}
function renewalDaysText(c){
  const end=c.finalEfectiva;if(!end)return'—';
  const days=daysBetween(startOfToday(),end);
  if(days<0)return`Vencido hace ${Math.abs(days)} día${Math.abs(days)===1?'':'s'}`;
  if(days===0)return'Vence hoy';
  return`${days} día${days===1?'':'s'}`;
}
function contractStatus(c){
  const today=startOfToday(),end=c.finalEfectiva;
  if(c.nuevaTramitacion&&/^EX-/i.test(c.nuevaTramitacion)){
    let label='En renovación'; if(end){const d=daysBetween(today,end);label=d>=0?`En renovación · ${d} día${d===1?'':'s'}`:'En renovación';}
    return{code:'RENOVACION',label,cls:'renovacion'};
  }
  if(!end)return{code:'SIN_FECHA',label:'Sin fecha definida',cls:'sin-fecha'};
  const days=daysBetween(today,end);
  if(days<0)return{code:'VENCIDO',label:`Vencido hace ${Math.abs(days)} día${Math.abs(days)===1?'':'s'}`,cls:'vencido'};
  if(days<=30)return{code:'CRITICO',label:days===0?'Vence hoy':`Vence en ${days} día${days===1?'':'s'}`,cls:'critico'};
  if(days<=90)return{code:'PROXIMO',label:`Vence en ${days} días`,cls:'proximo'};
  return{code:'VIGENTE',label:'Vigente',cls:'vigente'};
}
function populateContractFilters(){
  const setOptions=(id,values)=>{const el=document.getElementById(id),cur=el.value;el.innerHTML='<option value="ALL">Todas</option>'+values.map(v=>`<option>${escapeHtml(v)}</option>`).join('');if([...el.options].some(o=>o.value===cur))el.value=cur;};
  setOptions('contractCityFilter',[...new Set(state.contracts.map(c=>c.localidad))].sort((a,b)=>a.localeCompare(b,'es')));
  setOptions('processCityFilter',[...new Set(state.processContracts.map(c=>c.localidad))].sort((a,b)=>a.localeCompare(b,'es')));
}
function filteredContracts(){const city=document.getElementById('contractCityFilter').value,status=document.getElementById('contractStatusFilter').value,q=cleanText(document.getElementById('contractSearch').value).toLowerCase();return state.contracts.filter(c=>{const st=contractStatus(c);return(city==='ALL'||c.localidad===city)&&(status==='ALL'||st.code===status)&&(!q||`${c.contrato} ${c.empresa} ${c.expediente} ${c.nuevaTramitacion}`.toLowerCase().includes(q));});}
function renderContractStatusSummary(rows){const defs=[['VIGENTE','Vigentes','vigente'],['PROXIMO','Próximos a vencer (31–90 días)','proximo'],['CRITICO','Vencimiento crítico (≤ 30 días)','critico'],['RENOVACION','En renovación','renovacion'],['VENCIDO','Vencidos','vencido'],['SIN_FECHA','Sin fecha definida','sin-fecha']],counts=Object.fromEntries(defs.map(([c])=>[c,0]));rows.forEach(c=>counts[contractStatus(c).code]++);document.getElementById('contractStatusCards').innerHTML=defs.map(([c,label,cls])=>`<div class="status-row"><div class="left"><span class="dot ${cls}"></span><strong>${label}</strong></div><span class="count">${counts[c]}</span></div>`).join('');}
function renderContracts(){
  const rows=filteredContracts(),amount=rows.reduce((s,c)=>s+c.adjudicado,0),expiring=rows.filter(c=>['PROXIMO','CRITICO'].includes(contractStatus(c).code)),renewal=rows.filter(c=>contractStatus(c).code==='RENOVACION');
  document.getElementById('kpiContracts').textContent=NUM.format(rows.length);document.getElementById('kpiContractsAmount').textContent=fmtCompactMoney(amount);document.getElementById('kpiContractsExpiring').textContent=NUM.format(expiring.length);document.getElementById('kpiContractsRenewal').textContent=NUM.format(renewal.length);
  const future=rows.filter(c=>c.finalEfectiva&&c.finalEfectiva>=startOfToday()).sort((a,b)=>a.finalEfectiva-b.finalEfectiva);document.getElementById('kpiNextContractEnd').textContent=future[0]?`Próximo vencimiento: ${fmtDate(future[0].finalEfectiva)}`:'Próximo vencimiento: —';document.getElementById('contractsTableTotal').textContent=`${rows.length} contrato${rows.length===1?'':'s'} · ${fmtCompactMoney(amount)}`;renderContractStatusSummary(rows);
  const byCompany=new Map();rows.forEach(c=>byCompany.set(c.empresa,(byCompany.get(c.empresa)||0)+c.adjudicado));const companyData=[...byCompany.entries()].map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value);createBar('contractsCompanyChart','contractsCompanyChart',companyData.map(x=>x.name),companyData.map(x=>x.value),true);
  const sorted=[...rows].sort((a,b)=>{if(a.finalEfectiva&&b.finalEfectiva)return a.finalEfectiva-b.finalEfectiva;if(a.finalEfectiva)return-1;if(b.finalEfectiva)return 1;return a.contrato.localeCompare(b.contrato,'es');});
  document.getElementById('contractsBody').innerHTML=sorted.length?sorted.map(c=>{const st=contractStatus(c),renewal=/^EX-/i.test(c.nuevaTramitacion)?c.nuevaTramitacion:(c.nuevaTramitacion||'—');const extension=c.extensionEnd?`<span class="renewal-text">Prórroga detectada desde ${fmtDate(c.extensionStart)} hasta ${fmtDate(c.extensionEnd)}</span>`:'';return`<tr><td>${escapeHtml(c.localidad)}</td><td class="contract-name">${escapeHtml(c.contrato)}${extension}</td><td class="exp-cell">${escapeHtml(c.expediente)}</td><td class="numeric">${c.adjudicado?fmtMoney(c.adjudicado):'—'}</td><td class="company-cell">${escapeHtml(c.empresa)}</td><td>${c.plazo?`${NUM.format(c.plazo)} días`:'—'}</td><td>${fmtDate(c.inicio)}</td><td>${fmtDate(c.finalEfectiva)}</td><td><strong>${escapeHtml(renewalDaysText(c))}</strong></td><td><span class="status-pill ${st.cls}">${escapeHtml(st.label)}</span></td><td class="exp-cell">${escapeHtml(renewal)}</td></tr>`;}).join(''):'<tr><td class="empty-row" colspan="11">Sin contratos para los filtros seleccionados.</td></tr>';
}
function filteredProcessContracts(){const city=document.getElementById('processCityFilter').value,q=cleanText(document.getElementById('processSearch').value).toLowerCase();return state.processContracts.filter(c=>(city==='ALL'||c.localidad===city)&&(!q||`${c.contrato} ${c.expediente} ${c.empresa}`.toLowerCase().includes(q)));}
function renderProcessContracts(){const rows=filteredProcessContracts(),budget=rows.reduce((s,c)=>s+c.presupuesto,0),awarded=rows.reduce((s,c)=>s+c.adjudicado,0),cities=new Set(rows.map(c=>c.localidad));document.getElementById('kpiProcess').textContent=NUM.format(rows.length);document.getElementById('kpiProcessBudget').textContent=fmtCompactMoney(budget);document.getElementById('kpiProcessAwarded').textContent=fmtCompactMoney(awarded);document.getElementById('kpiProcessCities').textContent=NUM.format(cities.size);document.getElementById('processTableTotal').textContent=`${rows.length} trámite${rows.length===1?'':'s'}`;document.getElementById('processBody').innerHTML=rows.length?rows.map(c=>`<tr><td>${escapeHtml(c.localidad)}</td><td class="contract-name">${escapeHtml(c.contrato)}</td><td class="exp-cell">${escapeHtml(c.expediente)}</td><td class="numeric">${c.presupuesto?fmtMoney(c.presupuesto):'—'}</td><td class="numeric">${c.adjudicado?fmtMoney(c.adjudicado):'—'}</td><td>${escapeHtml(c.empresa)||'—'}</td><td>${c.plazo?`${NUM.format(c.plazo)} días`:'—'}</td><td>${fmtDate(c.inicio)}</td><td>${fmtDate(c.final)}</td></tr>`).join(''):'<tr><td class="empty-row" colspan="9">Sin tramitaciones para los filtros seleccionados.</td></tr>';}
async function loadDefaultContracts(){const status=document.getElementById('contractsFileStatus');status.textContent='Cargando archivo de contratos…';try{const b=await loadArrayBuffer(CONTRACTS_FILE);state.contracts=parseContracts(b);state.processContracts=parseProcessContracts(b);populateContractFilters();renderContracts();renderProcessContracts();document.getElementById('contractsBadge').textContent=state.contracts.length;document.getElementById('activeContractsCount').textContent=`(${state.contracts.length})`;document.getElementById('processContractsCount').textContent=`(${state.processContracts.length})`;status.textContent='Archivo base de contratos cargado';updateTimestamp(document.getElementById('contractsLastUpdate'));}catch(e){status.textContent=`Error: ${e.message}`;console.error(e);}}

// Eventos
document.getElementById('reloadDefault').addEventListener('click',loadDefaultCollection);document.getElementById('cityFilter').addEventListener('change',renderCollection);document.getElementById('channelFilter').addEventListener('change',renderCollection);
document.getElementById('reloadWorksDefault').addEventListener('click',loadDefaultWorks);document.getElementById('worksCityFilter').addEventListener('change',renderWorks);document.getElementById('worksStatusFilter').addEventListener('change',renderWorks);document.getElementById('worksSearch').addEventListener('input',renderWorks);
document.getElementById('reloadContractsDefault').addEventListener('click',loadDefaultContracts);document.getElementById('contractCityFilter').addEventListener('change',renderContracts);document.getElementById('contractStatusFilter').addEventListener('change',renderContracts);document.getElementById('contractSearch').addEventListener('input',renderContracts);document.getElementById('processCityFilter').addEventListener('change',renderProcessContracts);document.getElementById('processSearch').addEventListener('input',renderProcessContracts);

Promise.all([loadDefaultCollection(),loadDefaultWorks(),loadDefaultContracts()]);
